#!/usr/bin/env bash

# Use PHP 8.1 for Drupal 10.0.x
if [ -n "$DP_PHP" ] && [ "$DP_PHP" != '8.1' ]; then
    # Dynamically generate .ddev/config.gitpod.yaml file
cat <<GITMODULESEND > "${GITPOD_REPO_ROOT}"/.ddev/config.gitpod.yaml
# This file was dynamically generated by a script
php_version: "${DP_PHP}"
GITMODULESEND
fi
